question_data = [
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                       "question": "MacOS is based on Linux.", "correct_answer": "False",
                                       "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "question": "DHCP stands for Dynamic Host Configuration Port.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "Linux was first created as an alternative to Windows XP.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, "
                 "Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "A Boolean value of &quot;0&quot; represents which of these words?", "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
